# Generated by Django 4.0.4 on 2022-05-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, null=True)),
                ('categoria', models.CharField(choices=[('vestido', 'vestido'), ('camisa', 'camisa'), ('saia', 'saia')], max_length=20, null=True)),
                ('quantidade', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
