# Generated by Django 4.0.4 on 2022-05-02 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venda_quantidade', models.PositiveIntegerField(null=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('peca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.peca')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
