# Generated by Django 4.0.4 on 2022-05-07 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_venda'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peca',
            options={'verbose_name_plural': 'Peça'},
        ),
        migrations.AlterModelOptions(
            name='venda',
            options={'verbose_name_plural': 'Venda'},
        ),
    ]
